### PR TITLE
Add RSS feed to blog

### PR DESCRIPTION
**Pull request by chartgerink**
As a follow up to #129, I am adding the feed to the blog 😊 I tested it locally and it worked, and am happy to help ensure this is mergable to your standards 👍 

💜 

EDIT: Seeing the Netlify deploy, it may require a larger rebuild of the site to show up - I am not 100% sure how your build pipeline is set up I notice.

### CODE REVIEW

**Review by stefaniebutland — APPROVED** [review]
Thank you for this @chartgerink ! 

> Seeing the Netlify deploy, it may require a larger rebuild of the site to show up

Yes, currently we have to render the site locally and push `_site/` files. Andy Teucher will help us smooth this soon.

In my local preview, I see `blog.xml` created. Confession: I have never used an rss reader, so that's as far as my testing goes. 
I'm approving your pull request. Would you like me to render locally and merge?

**Comment by jules32** [comment]
Hi @stefaniebutland ! Yes would you please build locally and push/merge and we'll test it further from there :) Thank you both!

**Comment by jules32** [comment]
Hi @chartgerink , following up with this now that I'm back home from a conference. Thank you so much for contributing this, it is so valuable!

I have now rebuilt the whole website and republished. I attempted adding an icon to the top right of the top nav bar with th suggested location of `index.xml`(following https://quarto.org/docs/websites/website-blog.html#rss-feed), but this returned a 404 page. I am missing something.  

image


@chartgerink could you check that the RSS feed is working as you expect? And if you have another location to point the rss icon to rather than `index.xml` I can update that as well. 

Thank you!

**Comment by chartgerink** [comment]
@jules32 - you can use `/blog.xml` 👍  It is working perfectly: https://openscapes.org/blog.xml

Glad it was helpful 😊

**Comment by jules32** [comment]
Yay, thank you @chartgerink - it's now live! ([commit](https://github.com/Openscapes/website-new/commit/26654da5b39b543b50879e3e21ea2af5dd868670))

image

**Pull request merged**
