### PR TITLE
fixed event post categories so that they direct to the full events pa…

### PR DESCRIPTION
**Pull request by samanthacsik**
…ge listing, rather than the UPCOMING EVENTS listing on the Connect with Us page

@jules32 it seems like it was just a small yaml issue in `events.qmd`! See issue #62 for details.

### CODE REVIEW

**Comment by samanthacsik** [comment]
@jules32 Okay, everything things is working when I preview and build locally, but when I just took at look at the netlify preview, above, the **blog** listing is working as expected, but the **events** listing is now exhibiting the same weird behavior (clicking on a category takes you to **Connect with Us**, rather than the **Events** listing). 

My brain is slowing (lol) so I'm going to sleep on it and come back to it with fresh eyes in the AM!

**Comment by samanthacsik** [comment]
@jules32 I previewed locally just now again and both the Blog and Event tags on individual posts are redirecting back to the actual Blog or Event listing pages (which is good!). But the Netlify deploy preview shows only the Blog working now and the Events categories redirecting back to Connect with Us (odd, because I never changed anything there since I first opened the PR with that fix).

When you get a chance, I'm wondering if you can pull the `event-tags` branch and preview/build locally? I'm curious if the fixes worked for you locally as well, for both listings? Trying to figure out if it's a Netlify thing (which _would_ seem a bit odd)...

**Comment by jules32** [comment]
Hi! Yes thank you @samanthacsik, I will merge now and build locally and will report back!

**Comment by jules32** [comment]
Hi @samanthacsik, sorry that took me a while, I had to strategize about the merge conflicts :)

**Comment by samanthacsik** [comment]
oof, sorry to cause unintended merge conflicts 😅 -- I just looked at the site and it looks like this didn't actually fix the problem 😞 I'll do a bit more sleuthing and report back

**Pull request merged**
