### PR TITLE
Add Antoinette's post. TODO: format citations

### PR DESCRIPTION
**Pull request by stefaniebutland**

### CODE REVIEW

**Comment by stefaniebutland** [comment]
@jules32 two questions:

1. adding citations. I've added the items to [Openscapes Zotero library](https://www.zotero.org/groups/4118402/openscapes), but when I `Insert citation` in RStudio, and search for them I don't find them. Is there a "refresh" I need to do? (I've not used Zotero before)
1. How do I wrap Antoinette's bio text around her photo?

Screenshot 2024-08-08 at 9 27 53 PM

**Comment by jules32** [comment]
Hi Stef!

1. Quarto uses Zotero locally, not from the web. Do you have the app installed locally? If not, you'll need to download the Zotero app, login to sync from our library on the cloud, and then Quarto should be able to find them. If you already have it, yes there is a sync button: 
image. 
2. Yes, I would take the "2 column" strategy (don't have to be the same widths). https://forum.posit.co/t/picture-and-text-side-by-side-on-quarto/147682/5 shows code below - I would start with this and then tinker as needed. Full docs here: https://quarto.org/docs/output-formats/page-layout.html#css-grid

```
::: {.grid}

::: {.g-col-4}
This column takes 1/3 of the page
:::

::: {.g-col-8}
This column takes 2/3 of the page
:::

:::
```

**Comment by stefaniebutland** [comment]
Awesome thanks @jules32. I added a tiny bit on Zotero to [Approach Guide](https://openscapes.github.io/approach-guide/approach/tooling.html#zotero) and text wrap info to [website wiki](https://github.com/Openscapes/website-new/wiki/Adding-images#wrap-text-around-an-image)

**Comment by jules32** [comment]
Great Stef! Thank you!

**Pull request merged**
